### ISSUE TITLE
Clarification on first and second moral branch

### ISSUE THREAD

**Issue by g-simmons** [kmjohnson/twitter-morals#1]
Hi!

I am curious how the data was obtained for the first and second moral branch columns... in your paper you state that a subset of tweets were doubly-annotated by one liberal and one conservative annotator. Does this correspond to the first and second moral branch? If so, which one was the liberal annotator and which one conservative? Is it possible to indicate which annotator annotated each of the remaining examples? 

Any clarification is much appreciated!

**Comment by kmjohnson** [comment]
The first column represents the primary moral branch and the second column represents the secondary branch (if there is one). The 2 columns don't represent different annotators. The 2 annotators were used to verify the annotations and choose the final labels that appear in the CSV file.

**Comment by g-simmons** [comment]
Thanks for the quick response!

So when you say in the paper

> Annotators chose a primary moral foundation whenever possible, but were allowed a secondary foundation if the tweet presented two differing thoughts

"primary moral foundation" corresponds to the primary branch and "secondary foundation" corresponds to the secondary branch. Is that correct?

**Comment by kmjohnson** [comment]
Yes, exactly
