### ISSUE TITLE
Clarification on Moral Foundations

### ISSUE THREAD

**Issue by g-simmons** [kmjohnson/twitter-morals#2]
Is the following mapping from numbers 1 to 11 correct?

```
The Moral Foundations labels (1..11) are created like this: 
    if branch == 1 and polarity == 1:
		mf = 1 **CARE**
	elif branch == 1 and polarity == 2:
		mf = 2 **HARM**
	elif branch == 2 and polarity == 1:
		mf = 3 **FAIRNESS**
	elif branch == 2 and polarity == 2:
		mf = 4 **CHEATING**
	elif branch == 3 and polarity == 1:
		mf = 5 **LOYALTY**
	elif branch == 3 and polarity == 2:
		mf = 6 **BETRAYAL**
	elif branch == 4 and polarity == 1:
		mf = 7 **AUTHORITY**
	elif branch == 4 and polarity == 2:
		mf = 8 **SUBVERSION**
	elif branch == 5 and polarity == 1:
		mf = 9 **SANCTITY**
	elif branch == 5 and polarity == 2:
		mf = 10 **DEGRADATION**
(If cell 9 has the value of 6, then its MF = 11 **NONMORAL**)
```

**Comment by kmjohnson** [comment]
Yes, this is correct. I would note that 'nonmoral' just means none of the moral branches could be identified in the tweet, not that the tweet represents 'no morals'. Also, after this publication the MFT added a new branch _Liberty/Oppression_. So it's possible that many of these annotations could shift to fall under this newer branch given the political nature of this dataset.

**Comment by g-simmons** [comment]
Awesome, thank you.

There's also been a proposal to split up Fairness/Cheating https://psyarxiv.com/q6c9r/ into Equality and Proportionality 😄
